export const ITEMS_FETCH_STARTED = "ITEM_FETCH_STARTED";
export const ITEMS_FETCH_SUCCESS = "ITEM_FETCH_SUCCESS";
export const ITEMS_FETCH_ERRORED = "ITEM_FETCH_ERRORED";
export const CART_ADD_ITEM = "CARD_ADD_ITEM";
export const CART_DELETE_ITEM = "CARD_DELETE_ITEM";
export const CART_ADD_QTY = "CART_ADD_QTY";
export const CART_DEL_QTY = "CART_DEL_QTY";
